package com.xu.headline.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xu.headline.db.dbbean.SubscribeChannelDbBean;

import com.xu.headline.db.SubscribeChannelDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subscribeChannelDbBeanDaoConfig;

    private final SubscribeChannelDbBeanDao subscribeChannelDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subscribeChannelDbBeanDaoConfig = daoConfigMap.get(SubscribeChannelDbBeanDao.class).clone();
        subscribeChannelDbBeanDaoConfig.initIdentityScope(type);

        subscribeChannelDbBeanDao = new SubscribeChannelDbBeanDao(subscribeChannelDbBeanDaoConfig, this);

        registerDao(SubscribeChannelDbBean.class, subscribeChannelDbBeanDao);
    }
    
    public void clear() {
        subscribeChannelDbBeanDaoConfig.clearIdentityScope();
    }

    public SubscribeChannelDbBeanDao getSubscribeChannelDbBeanDao() {
        return subscribeChannelDbBeanDao;
    }

}
