package com.xu.headline.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xu.headline.db.helper.NewsHistoryConvert;
import java.util.List;

import com.xu.headline.db.dbbean.NewsHistoryDbBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_HISTORY_DB_BEAN".
*/
public class NewsHistoryDbBeanDao extends AbstractDao<NewsHistoryDbBean, Long> {

    public static final String TABLENAME = "NEWS_HISTORY_DB_BEAN";

    /**
     * Properties of entity NewsHistoryDbBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ChannelID = new Property(1, String.class, "channelID", false, "CHANNEL_ID");
        public final static Property Time = new Property(2, long.class, "time", false, "TIME");
        public final static Property NewsItems = new Property(3, String.class, "newsItems", false, "NEWS_ITEMS");
    }

    private final NewsHistoryConvert newsItemsConverter = new NewsHistoryConvert();

    public NewsHistoryDbBeanDao(DaoConfig config) {
        super(config);
    }
    
    public NewsHistoryDbBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_HISTORY_DB_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CHANNEL_ID\" TEXT," + // 1: channelID
                "\"TIME\" INTEGER NOT NULL ," + // 2: time
                "\"NEWS_ITEMS\" TEXT);"); // 3: newsItems
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_HISTORY_DB_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsHistoryDbBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String channelID = entity.getChannelID();
        if (channelID != null) {
            stmt.bindString(2, channelID);
        }
        stmt.bindLong(3, entity.getTime());
 
        List newsItems = entity.getNewsItems();
        if (newsItems != null) {
            stmt.bindString(4, newsItemsConverter.convertToDatabaseValue(newsItems));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsHistoryDbBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String channelID = entity.getChannelID();
        if (channelID != null) {
            stmt.bindString(2, channelID);
        }
        stmt.bindLong(3, entity.getTime());
 
        List newsItems = entity.getNewsItems();
        if (newsItems != null) {
            stmt.bindString(4, newsItemsConverter.convertToDatabaseValue(newsItems));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public NewsHistoryDbBean readEntity(Cursor cursor, int offset) {
        NewsHistoryDbBean entity = new NewsHistoryDbBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // channelID
            cursor.getLong(offset + 2), // time
            cursor.isNull(offset + 3) ? null : newsItemsConverter.convertToEntityProperty(cursor.getString(offset + 3)) // newsItems
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsHistoryDbBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChannelID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTime(cursor.getLong(offset + 2));
        entity.setNewsItems(cursor.isNull(offset + 3) ? null : newsItemsConverter.convertToEntityProperty(cursor.getString(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NewsHistoryDbBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NewsHistoryDbBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewsHistoryDbBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
